apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "mailcow.fullname" . }}-redis
  ports:
    - port: 6379
      name: redis
