{{- if or (eq .Values.tls.cert.secretKeyRef.nameSuffix "tls-default") (eq .Values.tls.key.secretKeyRef.nameSuffix "tls-default") (eq .Values.tls.dhparams.secretKeyRef.nameSuffix "tls-default") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mailcow.fullname" . }}-tls-default
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if eq .Values.tls.cert.secretKeyRef.nameSuffix "tls-default" }}
  cert.pem: | {{- .Files.Get "data/assets/ssl-example/cert.pem" | nindent 4 }}
  {{- end -}}
  {{- if eq .Values.tls.key.secretKeyRef.nameSuffix "tls-default" }}
  key.pem: | {{- .Files.Get "data/assets/ssl-example/key.pem" | nindent 4 }}
  {{- end -}}
  {{- if eq .Values.tls.dhparams.secretKeyRef.nameSuffix "tls-default" }}
  dhparams.pem: | {{- .Files.Get "data/assets/ssl-example/dhparams.pem" | nindent 4 }}
  {{- end -}}
{{- end -}}
