apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "mailcow.fullname" . }}-mariadb
  ports:
    - port: 3306
      name: mysql
